Feature
zsh28/travel-planner pull request #10
Opened 2024-04-05 20:02 UTC by zsh28

2024-04-05 23:14 UTC, SwyftPain requested changes
There are some  conflicts i cant fix myself via web editor. There are also some extra uneccessary things, doing it as 2 separate states or functions when it could be a single toggle. Comments added where its obvious what the code does. Needs changes

2024-04-05 23:14 UTC, SwyftPain commented on App.tsx
> +            headerLeft: () => {
Is vanity but no issue here

2024-04-05 23:14 UTC, SwyftPain commented on Screens/Home.tsx
> +  //set modal to visible -> True
Toggle function would possibly be better than 2 separate states that always turns to opposite of the current state

2024-04-05 23:14 UTC, SwyftPain commented on Screens/Login.tsx
> +  //function to login
Should be obvious without the comment

2024-04-08 12:27 UTC, avrey-s approved these changes
This looks well done to me.

2024-04-10 08:33 UTC, SwyftPain approved these changes

2024-04-10 08:35 UTC, SwyftPain approved these changes

2024-04-10 17:03 UTC, avrey-s approved these changes

2024-04-10 17:03 UTC, merged