Feature: API Added
zsh28/travel-planner pull request #14
Opened 2024-04-18 13:21 UTC by zsh28

2024-04-18 13:36 UTC, SwyftPain requested changes
Some minor inconsistencies which are fine. The versions in package.json need to be edited.

Some abstractions or components could be used like <Button /> rather than recreating it again.

Also with changes like putting 2 headers in a file, if not screenshots, would be at least nice to have a message/comment to know what exactly was being added with the PR, since its not just creating API functions, it is actually adding/editing other files as well.

So in that sense, just "API Added" is not clear enough description.

Possibly better solution would be to provide bulletpoints, saying what files were edited, how and why in a short sentence.

2024-04-18 13:36 UTC, SwyftPain commented on Screens/Home.tsx
> +  const ToggleModal = () => {
Inconsistent casing. JavaScript/TypeScript mainly uses camel-case. Meaning first letter is lowercase.
Your togglePicker function follows this standard. ToggleModal doesn't. Not a big deal and can be fixed in a later formatting/consistency PR but just a note to remember :)

2024-04-18 13:36 UTC, SwyftPain commented on Screens/Home.tsx
> +      console.log("Flight Data Received:", flightData);
These logs are probably not needed beyond/after testing and actual implementation. Once the app is built, you won't be able to see them anywhere anyway.

2024-04-18 13:36 UTC, SwyftPain commented on Screens/Home.tsx
> +            <TouchableOpacity onPress={togglePicker}>
We already made a Button component, we could have just used that. If it didn't have needed props on it, just add them.

2024-04-18 13:36 UTC, SwyftPain commented on Screens/Settings.tsx
>        <Header headerTitle={"Change Password"} />
Slightly confused, do we have two headers in the same file?

2024-04-18 13:36 UTC, SwyftPain commented on Styles/DarkStyles.tsx
> +  //close icon
isn't this obvious its close icon?

2024-04-18 13:36 UTC, SwyftPain commented on api/weather.tsx
> +    'X-RapidAPI-Key': '5bda5892bfmsh0930416066adb65p16c0bcjsnf58b3e7581bf',
Do we want this info in our code? (Benefit of the doubt, could be from documentation example)

2024-04-18 13:36 UTC, SwyftPain commented on api/weather.tsx
> +  };
Formatting inconsistency, new lines, etc

2024-04-18 13:36 UTC, SwyftPain commented on package.json
> +    "fast-xml-parser": "^4.3.6",
The ^ symbol should be removed

2024-04-18 13:36 UTC, SwyftPain commented on package.json
> +    "react-native-modern-datepicker": "^1.0.0-beta.91",
The ^ symbol should be removed

2024-04-18 13:36 UTC, SwyftPain commented on package.json
> +    "@types/react-native-modern-datepicker": "^1.0.5",
The ^ symbol should be removed

2024-04-18 14:03 UTC, SwyftPain approved these changes
Seems good now, i appreciate some consistency changes.

2024-04-19 17:49 UTC, avrey-s approved these changes

2024-04-19 18:04 UTC, merged